# Generated by Django 5.2.14 on 2026-05-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='country_of_residence',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('ja', 'Japanese'), ('ru', 'Russian'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('hi', 'Hindi')], default='en', max_length=10),
        ),
    ]
