# Generated by Django 5.2.14 on 2026-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Designates if user can buy/browse as a client.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_store_owner',
            field=models.BooleanField(default=False, help_text='Designates if user owns a business/spot.'),
        ),
    ]
