# Generated by Django 5.2.14 on 2026-05-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_country_of_residence_usersettings_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Setting', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='user_settings',
        ),
    ]
