# Generated by Django 5.2.14 on 2026-06-05 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_alter_spot_options_alter_spot_table'),
        ('users', '0002_user_is_client_alter_user_is_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='active_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spots.spot'),
        ),
    ]
