# Generated by Django 5.2.14 on 2026-05-27 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtickettier',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='spots.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='ticket_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='spots.eventtickettier'),
        ),
        migrations.AddField(
            model_name='operatinghours',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='spots.spot'),
        ),
        migrations.AddField(
            model_name='itemforsale',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spots.spot'),
        ),
        migrations.AddField(
            model_name='event',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='spots.spot'),
        ),
        migrations.AddField(
            model_name='spotmember',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='spots.spot'),
        ),
        migrations.AddField(
            model_name='spotmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'user', 'ticket_tier'), name='unique_user_ticket_per_event'),
        ),
        migrations.AlterUniqueTogether(
            name='operatinghours',
            unique_together={('spot', 'day')},
        ),
        migrations.AddConstraint(
            model_name='spotmember',
            constraint=models.UniqueConstraint(fields=('spot', 'user'), name='unique_spot_user_role'),
        ),
    ]
