# Generated by Django 5.2.14 on 2026-06-04 16:37

import utils.upload.image_handler
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.image_handler.ImageUploadHandler('shops/licenses/')),
        ),
    ]
