# Generated by Django 5.2.14 on 2026-06-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_spot_business_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Spot', 'verbose_name_plural': 'Spots'},
        ),
        migrations.AlterModelTable(
            name='spot',
            table='spots',
        ),
    ]
