# Generated by Django 5.2.14 on 2026-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_alter_spot_options_alter_spot_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
