# Generated by Django 5.2.14 on 2026-06-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_spotinvitation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spotinvitation',
            table='spot_invitations',
        ),
    ]
