# Generated by Django 5.2.14 on 2026-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_alter_spotinvitation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
