# Generated by Django 5.2.14 on 2026-06-09 09:16

import utils.upload.image_handler
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0013_serviceimage_created_at_serviceimage_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=utils.upload.image_handler.ImageUploadHandler('products/gallery/')),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to=utils.upload.image_handler.ImageUploadHandler('services/gallery/')),
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
        migrations.AlterModelTable(
            name='serviceimage',
            table='service_images',
        ),
    ]
