# Generated by Django 5.2.14 on 2026-06-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0014_alter_service_options_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventtickettier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemforsale',
            options={},
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='eventregistration',
            table='registration_status',
        ),
        migrations.AlterModelTable(
            name='eventtickettier',
            table='even_ticket_tier',
        ),
        migrations.AlterModelTable(
            name='itemforsale',
            table='items_for_sale',
        ),
        migrations.AlterModelTable(
            name='operatinghours',
            table='operating_hours',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
        migrations.AlterModelTable(
            name='spotmember',
            table='spot_members',
        ),
    ]
