# Generated by Django 5.2.14 on 2026-06-22 09:44

import django.db.models.deletion
import utils.upload.image_handler
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0016_event_category_eventorder_eventregistration_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to=utils.upload.image_handler.VideoUploadHandler('spots/feed/videos/'))),
                ('video_cover', models.ImageField(blank=True, null=True, upload_to=utils.upload.image_handler.ImageUploadHandler('spots/feed/covers/'))),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.CharField(blank=True, max_length=500)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_watch_time_seconds', models.PositiveIntegerField(default=0)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='spots.spot')),
            ],
            options={
                'db_table': 'feed_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedViewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='spots.feeditem')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_view_logs',
            },
        ),
    ]
