# Generated by Django 5.2.14 on 2026-06-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0018_feedboost_feedcomment_feedlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='spots.feedcomment'),
        ),
    ]
