# Generated by Django 5.2.14 on 2026-06-24 09:10

import cloudinary_storage.storage
import utils.upload.image_handler
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0019_feedcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='video_file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to=utils.upload.image_handler.VideoUploadHandler('spots/feed/videos/')),
        ),
    ]
