# Generated by Django 5.2.14 on 2026-06-24 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0020_alter_feeditem_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target', models.CharField(choices=[('all_services', 'All Services'), ('all_products', 'All Products'), ('specific_items', 'Specific Items')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='spots.product')),
                ('services', models.ManyToManyField(blank=True, related_name='promotions', to='spots.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
